version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./prometheus/data:/prometheus"
      - "./alertmanager/alert.yml:/etc/prometheus/rules/alert.yml"
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.external-url=http://192.168.80.1:9090'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention=15d'

  grafana:
    image: grafana/grafana
    container_name: "grafana"
    ports:
      - "9000:3000"
    restart: always
    volumes:
      - "./grafana/grafana_data:/var/lib/grafana"

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    hostname: alertmanager
    restart: always
    ports:
      - '9093:9093'
    volumes:
      - './alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml'
      - './alertmanager/template/webhook.tmpl:/etc/alertmanager/template/webhook.tmpl'

  prometheus-alert:
    build: .
    image: webhook:v2
    container_name: prometheus-alert
    hostname: prometheus-alert
    restart: always
    ports:
      - "9094:9094"