GET https://192.168.253.129:6443/metrics

Authorization: bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IlZEVlh0alZWV3MyRU5ScXFKcklaSVpubHlHbW1wdGRUUU9qSnJoVHp5QUUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbi10b2tlbi13aHE2dCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImNhMDMzYWVhLTE3ZDYtNDRmOC05ZjI2LTBlMjNhMGNmMTZhZCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTphZG1pbiJ9.e0d6UT-sMfeOzVmBTfwcPyjiS9ZG30h6ex_1ZtU3yeI5UaknXmHN3Fz_L0miEy1FIIFDn9swDJEMftVTuEFJt_ot4RyQw0mVIqwAB25QNy-IvNktyY-bMwkZpcyPUVDITdBwZtBGuDaOcngHoasSP_6TdkeDMoKniobR4j-VKxjYQCJsUyGoJpzCxstR5OdoD7REuc80muL5j8AXipmT7-RxiNEGZsxWHB3X37lWtCzhFkGY4-BXb6B0vL8ZA0Ijv1xpc87M02pfc0tlWCLLZ_DY8_mF84NgHaLAUmUpPZdMjLs06hwlLRzcI2K86m3CYXypDoRJ44EZaFFHCUE1Hw

###
