global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    bearer_token_file: /prometheus/k8s_token
    kubernetes_sd_configs:
    - role: node
      api_server: 'https://192.168.253.135:6443'
      tls_config:
        insecure_skip_verify: true
      bearer_token_file: /prometheus/k8s_token

    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.*)
      - action: replace
        regex: (.*)
        source_labels: [ __address__ ]
        target_label: __address__
        replacement: 192.168.253.135:6443
      - action: replace
        source_labels: [ __meta_kubernetes_node_name ]
        target_label: __metrics_path__
        regex: (.*)
        replacement: /api/v1/nodes/${1}/proxy/metrics

  - job_name: 'pod'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    bearer_token_file: /prometheus/k8s_token
    kubernetes_sd_configs:
      - role: node
        api_server: 'https://192.168.253.135:6443'
        tls_config:
          insecure_skip_verify: true
        bearer_token_file: /prometheus/k8s_token

    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.*)
      - action: replace
        regex: (.*)
        source_labels: [ __address__ ]
        target_label: __address__
        replacement: 192.168.253.135:6443
      - action: replace
        source_labels: [ __meta_kubernetes_node_name ]
        target_label: __metrics_path__
        regex: (.*)
        replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

rule_files:
  - "/etc/prometheus/rules/*.yml"